# Generated by Django 3.2.4 on 2021-06-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_owner_shop_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
