# Generated by Django 3.2.4 on 2021-06-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
