# Generated by Django 3.2.4 on 2021-06-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cash_customer_customer_cost_customer_pay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
