# Generated by Django 3.2.4 on 2021-06-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop_name',
        ),
    ]
