# Generated by Django 3.2.4 on 2021-06-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_name_shop_shop_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
