# Generated by Django 3.2.4 on 2021-06-21 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0009_remove_cash_pay_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash', to=settings.AUTH_USER_MODEL),
        ),
    ]
