# Generated by Django 3.2.4 on 2021-06-21 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_alter_cash_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Cost_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('describe', models.CharField(max_length=200)),
                ('cost', models.BooleanField()),
                ('pay', models.BooleanField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_pay', to='shop.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer_pay',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer_pay',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer_Cost',
        ),
        migrations.DeleteModel(
            name='Customer_Pay',
        ),
    ]
