# Generated by Django 3.2.4 on 2021-06-21 18:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_supplier_supplierr_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplierr_Cost',
            new_name='Supplier_Cost',
        ),
    ]
