# Generated by Django 3.2.4 on 2021-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_cash_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
