# Generated by Django 3.2.4 on 2021-06-22 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_cash_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 15, 0, 55, 774592)),
        ),
    ]
