# Generated by Django 4.0.5 on 2022-06-21 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20211021_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 50, 10, 387512)),
        ),
        migrations.AlterField(
            model_name='customer_cost_pay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 50, 10, 386085)),
        ),
    ]
